apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::450963613786:role/eksctl-cluster-addon-iamserviceaccount-defaul-Role1-bzr1mWeovj5m
