FROM node:22-alpine

WORKDIR /app

# שלב 1 - תלויות בלבד (יציב, משתנה לעיתים רחוקות)
COPY package*.json ./

RUN npm ci

# שלב 2 - קוד האפליקציה (משתנה תכוף)
COPY . .

EXPOSE 3000

CMD ["node", "index.js"]

