apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          # WARNING: tag שגוי בכוונה - חסר מינוס בין 1 ל-alpine
          # הtag הנכון הוא nginx:1.27.1-alpine
          # קובץ זה לtרגול debugging בלבד - אל תשתמש בproduction
          image: nginx:1.27.1alpine
          ports:
            - containerPort: 80
