

apiVersion: v1
kind: Namespace
metadata:
  name: storage-reclaim-lab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reclaim-demo-pvc
  namespace: storage-reclaim-lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
